# Generated by Django 4.1.10 on 2023-07-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="target_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_target",
                to="contenttypes.contenttype",
            ),
        ),
    ]
